name: Docker Image CI

on:
  push:
    # Triggers the workflow on push events but only for the master branch
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_publish:
    name: Build test and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd nest/NestJsORM
            sudo rm -r letsencrypt
            git pull
            docker-compose down
            docker rmi thanhdeveloper/nest:master
            docker rmi traefik:v2.4
            docker-compose up -d
            sudo service status nginx
            exit